# Generated by Django 4.2.2 on 2023-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("items", models.CharField(max_length=200)),
                ("lat_long", models.CharField(max_length=200)),
                ("full_details", models.TextField()),
            ],
        ),
    ]
